# Site settings
title:  Xymmh's Blog
SEOTitle: DoHaveFaith
header-img: img/IMG_0254-DeNoiseAI-standard.jpg
email: my@havfaith.cn
description: "Do have faith in what you are doing."
keyword: "Xymmh's Blog, DoHaveFaith, Xymmh的博客"
url: "https://xymmh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xymmh/xymmh.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "北京工业大学学生"
sidebar-avatar: /img/Myavatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
weibo_username:     1035998644
zhihu_username:     meng-hu-83-39
github_username:    Xymmh
facebook_username:  Xymmh
#jianshu_username:	jianshu_id

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 13
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jemoji,jekyll-sitemap]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 评论系统
# Gitalk
gitalk:
  enable: true   #是否开启Gitalk评论
  clientID: 5943aeedd7ee1a1cbdf7        # 嘿，别乱看我的秘密                #生成的clientID
  clientSecret: 4ffbc9e4eb8b6aef2b390b2bda69ed6a744c5c07    #生成的clientSecret
  repo: Xymmh.github.io    #仓库名称
  owner: Xymmh    #github用户名
  admin: Xymmh
  distractionFreeMode: false #是否启用类似FB的阴影遮罩
  perPage: 15

# 统计
# Analytics settings
ga_track_id: 'G-BJXHC5H6Q1'
ga_domain: auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1             # 相同标签数量大于这个数，才会出现在首页

# Friends
friends: [
    {
        title: "北京大学网络服务",
        href: "https://its.pku.edu.cn/"
    },{
        title: "求闻百科",
        href: "https://www.qiuwenbaike.cn/"
    }    
]
